# Generated by Django 4.2.2 on 2023-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cocktail_recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("recipe", models.TextField(verbose_name="Рецепт")),
                ("string_ings", models.TextField(verbose_name="Ингредиенты")),
                ("string_tags", models.TextField(verbose_name="Пожелания")),
            ],
        ),
    ]
